name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: publish
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - name: publish
        uses: JS-DevTools/npm-publish@v1
        token: ${{ secrets.NPM_TOKEN }}
